var studentdata = new Vue({
    el: '#us',
    data: {
        image: "https://bit.ly/2U2OCs0",
        stuname: "",
        counter: 0,
        oswald: "nothing yet",
        divStructure: {
            backgroundColor: '#c0ffee',
            width: '400px'
        },
        divText: {
            fontFamily: 'Arial',
            fontStyle: 'bold',
            color: 'blue'
        },
        yall: [{
            "0": "Abbey",
            "stu_name": "Abbey",
            "1": "Miner",
            "last_name": "Miner",
            "2": "abbeylminer.com\/7110",
            "domain": "abbeylminer.com\/7110",
            "3": "12305110",
            "section": "12305110",
            "4": "Hi, I'm Abbey! I love dogs and bagels and smiling. I'm an EM grad student and am peacing out in December to head back into the real world.",
            "fact": "Hi, I'm Abbey! I love dogs and bagels and smiling. I'm an EM grad student and am peacing out in December to head back into the real world.",
            "5": "",
            "freecode": "",
            "6": "262",
            "count": "262"
        }, {
            "0": "Bailey",
            "stu_name": "Bailey",
            "1": "Pelletier",
            "last_name": "Pelletier",
            "2": "baileypelletier.com",
            "domain": "baileypelletier.com",
            "3": "12305110",
            "section": "12305110",
            "4": "I love photography, Georgia Football, and have no idea what I'll be doing in 4 years.",
            "fact": "I love photography, Georgia Football, and have no idea what I'll be doing in 4 years.",
            "5": "",
            "freecode": "",
            "6": "256",
            "count": "256"
        }, {
            "0": "Caroline ",
            "stu_name": "Caroline ",
            "1": "Windham",
            "last_name": "Windham",
            "2": "cwwwindham.com",
            "domain": "cwwwindham.com",
            "3": "12305110",
            "section": "12305110",
            "4": " I have been in a children's book.",
            "fact": " I have been in a children's book.",
            "5": "",
            "freecode": "",
            "6": "261",
            "count": "261"
        }, {
            "0": "Christian",
            "stu_name": "Christian",
            "1": "Guerrero",
            "last_name": "Guerrero",
            "2": "guerreroc.com\/5110",
            "domain": "guerreroc.com\/5110",
            "3": "12305110",
            "section": "12305110",
            "4": " I am a 4th year CS major and I play the guitar!",
            "fact": " I am a 4th year CS major and I play the guitar!",
            "5": "",
            "freecode": "",
            "6": "267",
            "count": "267"
        }, {
            "0": "Claire",
            "stu_name": "Claire",
            "1": "Jordan",
            "last_name": "Jordan",
            "2": "clairebeth.com",
            "domain": "clairebeth.com",
            "3": "12305110",
            "section": "12305110",
            "4": " Hi! I play the piano!",
            "fact": " Hi! I play the piano!",
            "5": "",
            "freecode": "",
            "6": "257",
            "count": "257"
        }, {
            "0": "Dakota ",
            "stu_name": "Dakota ",
            "1": "Werner",
            "last_name": "Werner",
            "2": "dakotawerner.com\/nmi\/5110",
            "domain": "dakotawerner.com\/nmi\/5110",
            "3": "12305110",
            "section": "12305110",
            "4": "I traveled abroad for the first time this summer and went to 5 countries!",
            "fact": "I traveled abroad for the first time this summer and went to 5 countries!",
            "5": "",
            "freecode": "",
            "6": "254",
            "count": "254"
        }, {
            "0": "Daniel",
            "stu_name": "Daniel",
            "1": "Copetillo",
            "last_name": "Copetillo",
            "2": "danielcopetillo.com\/nmi\/5110",
            "domain": "danielcopetillo.com\/nmi\/5110",
            "3": "12305110",
            "section": "12305110",
            "4": "Nick Cage is the best actor of all time. Change my mind.",
            "fact": "Nick Cage is the best actor of all time. Change my mind.",
            "5": "",
            "freecode": "",
            "6": "251",
            "count": "251"
        }, {
            "0": "Eddie",
            "stu_name": "Eddie",
            "1": "Gu",
            "last_name": "Gu",
            "2": "eddiegu666.com\/nmi5110",
            "domain": "eddiegu666.com\/nmi5110",
            "3": "12305110",
            "section": "12305110",
            "4": " dog, sports",
            "fact": " dog, sports",
            "5": "",
            "freecode": "",
            "6": "258",
            "count": "258"
        }, {
            "0": "Evan",
            "stu_name": "Evan",
            "1": "Whitehead",
            "last_name": "Whitehead",
            "2": "whiteheadevan1.com",
            "domain": "whiteheadevan1.com",
            "3": "12305110",
            "section": "12305110",
            "4": "From Indiana originally, moved to Forsyth County when I was 7. Then Started college at Kennesaw and eventually transferred to UGA!\r\n\r\nLove hiking, running, and started rock climbing over this past Summer!",
            "fact": "From Indiana originally, moved to Forsyth County when I was 7. Then Started college at Kennesaw and eventually transferred to UGA!\r\n\r\nLove hiking, running, and started rock climbing over this past Summer!",
            "5": "",
            "freecode": "",
            "6": "259",
            "count": "259"
        }, {
            "0": "Evan",
            "stu_name": "Evan",
            "1": "Whitehead",
            "last_name": "Whitehead",
            "2": "whiteheadevan.com",
            "domain": "whiteheadevan.com",
            "3": "12305110",
            "section": "12305110",
            "4": "Love being hiking, running, climbing. Grew up in Cumming GA, born in Indianapolis.",
            "fact": "Love being hiking, running, climbing. Grew up in Cumming GA, born in Indianapolis.",
            "5": "",
            "freecode": "",
            "6": "329",
            "count": "329"
        }, {
            "0": "Jack",
            "stu_name": "Jack",
            "1": "Towery",
            "last_name": "Towery",
            "2": "jacktowery.com",
            "domain": "jacktowery.com",
            "3": "12305110",
            "section": "12305110",
            "4": "I love camping in the mountains",
            "fact": "I love camping in the mountains",
            "5": "",
            "freecode": "",
            "6": "263",
            "count": "263"
        }, {
            "0": "Mary Claire",
            "stu_name": "Mary Claire",
            "1": "Murdock",
            "last_name": "Murdock",
            "2": "maryclairemurdock.com\/nmi5110",
            "domain": "maryclairemurdock.com\/nmi5110",
            "3": "12305110",
            "section": "12305110",
            "4": "I have a toe thumb",
            "fact": "I have a toe thumb",
            "5": "",
            "freecode": "",
            "6": "255",
            "count": "255"
        }, {
            "0": "Meghan",
            "stu_name": "Meghan",
            "1": "Telling",
            "last_name": "Telling",
            "2": "meghantelling.com\/nmi\/5110",
            "domain": "meghantelling.com\/nmi\/5110",
            "3": "12305110",
            "section": "12305110",
            "4": " Big fan of Steve Harvey. ",
            "fact": " Big fan of Steve Harvey. ",
            "5": "",
            "freecode": "",
            "6": "252",
            "count": "252"
        }, {
            "0": "Meredith",
            "stu_name": "Meredith",
            "1": "Tilton",
            "last_name": "Tilton",
            "2": "meredithtilton.com",
            "domain": "meredithtilton.com",
            "3": "12305110",
            "section": "12305110",
            "4": "I love listening to and playing music! ",
            "fact": "I love listening to and playing music! ",
            "5": "",
            "freecode": "",
            "6": "253",
            "count": "253"
        }, {
            "0": "Saloni",
            "stu_name": "Saloni",
            "1": "Gupta",
            "last_name": "Gupta",
            "2": "salonigupta10.com",
            "domain": "salonigupta10.com",
            "3": "12305110",
            "section": "12305110",
            "4": " I have lived in 5 states: Connecticut, New Jersey, California, Kansas, Georgia. ",
            "fact": " I have lived in 5 states: Connecticut, New Jersey, California, Kansas, Georgia. ",
            "5": "",
            "freecode": "",
            "6": "265",
            "count": "265"
        }, {
            "0": "Sarah",
            "stu_name": "Sarah",
            "1": "Jacobson",
            "last_name": "Jacobson",
            "2": "sarahtjacobson.com",
            "domain": "sarahtjacobson.com",
            "3": "12305110",
            "section": "12305110",
            "4": " I am a 3rd year Advertising major with a minor in Communication Studies and the New Media Certificate. This summer I went to the Cannes Lions Festival for a study abroad with Grady College. ",
            "fact": " I am a 3rd year Advertising major with a minor in Communication Studies and the New Media Certificate. This summer I went to the Cannes Lions Festival for a study abroad with Grady College. ",
            "5": "",
            "freecode": "",
            "6": "260",
            "count": "260"
        }, {
            "0": "Sydney",
            "stu_name": "Sydney",
            "1": "Norris",
            "last_name": "Norris",
            "2": "sydnorris.com",
            "domain": "sydnorris.com",
            "3": "12305110",
            "section": "12305110",
            "4": " I am the 3rd person in my family to graduate from UGA.",
            "fact": " I am the 3rd person in my family to graduate from UGA.",
            "5": "",
            "freecode": "",
            "6": "266",
            "count": "266"
        }, {
            "0": "Zach",
            "stu_name": "Zach",
            "1": "McMurry",
            "last_name": "McMurry",
            "2": "zachmcmurry.com",
            "domain": "zachmcmurry.com",
            "3": "12305110",
            "section": "12305110",
            "4": " I have climbed the third tallest volcano in Central America ",
            "fact": " I have climbed the third tallest volcano in Central America ",
            "5": "",
            "freecode": "",
            "6": "264",
            "count": "264"
        }]
    },
    computed: {
        title() {
            let whichYall = Math.floor(Math.random() * this.yall.length);
            return this.yall[whichYall].stu_name + ' ' + this.yall[whichYall].last_name;
        }
    }

})